name = "quakeshack-engine"
main = "source/cloudflare/worker.mjs"
compatibility_date = "2025-01-01"

workers_dev = false
preview_urls = false

[build]
command = "npm run build:wrangler"

[assets]
directory = "dist/browser"
binding = "ASSETS"

[[routes]]
pattern = "play.quakeshack.dev"
custom_domain = true
